### PR TITLE
Fixed gain/loss of resource in transfers

### PR DESCRIPTION
**Pull request by arivaldh**
Fixed gain/loss or resource in multitank to multitank transfers.
Also:
  - better comments!
  - variable name changes in order to reflect their purpose
  - creation of intermediate list in order not to duplicate skip
  conditions (if they change in only one loop where doomed)

### CODE REVIEW

**Comment by arivaldh** [comment]
Please merge or discuss why it's not being merged.

**Comment by arivaldh** [comment]
I have removed the use of Enumerator since:
"The foreach statement of the C# language (for each in C++, For Each in Visual Basic) hides the complexity of enumerators. Therefore, using foreach is recommended, instead of directly manipulating the enumerator."
https://msdn.microsoft.com/en-us/library/x854yt9s(v=vs.110).aspx

And I personally don't like them, since they give us nothing more than foreach. And foreach is cleaner.
I have tested the change for multiple Solar Panels per Part.

**Comment by PapaJoesSoup** [comment]
That is true when using C# with the Microsoft garbage collector.  However, the Mono garbage collector Used in Unity does not play well with Foreach.  Therefore you end up with a significant amount of orphaned objects, reducing your available memory.  So to combat this the use of enumerators avoids the additional object generation in Mono, and reduces the garbage footprint.

**Comment by arivaldh** [comment]
Ok. Then I'll restore use of Enumerator. And try to find the issue with Antennas that's bugging my campaign.

**Comment by arivaldh** [comment]
Changed merge to:
from: arivaldh:master
to: PapaJoesSoup:Dev

**Comment by arivaldh** [comment]
I have fixed Antenna Control when RemoteTech is present.
For now I'll be switching to different tasks.

**Comment by arivaldh** [comment]
Anything going on? Do you need anything more?

**Pull request merged**
